# Generated by Django 3.2 on 2021-04-17 22:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('client_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50)),
                ('unit_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recipe', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='icecreamshop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecreamshop.product')),
            ],
        ),
    ]
