# Generated by Django 3.2 on 2021-04-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecreamshop', '0003_auto_20210418_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
